### ISSUE TITLE
is CPUFriendDataProvider.kext for the 6200u?

### ISSUE THREAD

**Issue by sakoula** [johnnync13/Xiaomi-Notebook-Air-6200u#3]
Hi I noticed that the CPUFriendDataProvider.kext  is identical with the [daliansky/XiaoMi-Pro](https://github.com/daliansky/XiaoMi-Pro).

However this is a totally different CPU. Is it compatible? Can you please explain how you produced it?

Thanks!

**Comment by johnnync13** [comment]
@sakoula use this for create dataprovider https://github.com/acidanthera/CPUFriend/blob/master/ResourceConverter/ResourceConverter.sh
