### ISSUE TITLE
ALCPlugFix how to figure the hda-verb needed to pass

### ISSUE THREAD

**Issue by sakoula** [johnnync13/Xiaomi-Notebook-Air-6200u#5]
Hi!

I am trying to figure out the ALCPlugFix. How do you figure out which hda-verb to pass when for the ALCPlugFix? 

Thanks!

**Comment by johnnync13** [comment]
I use his page for learn more about hackintosh http://blog.daliansky.net/hda-verb-parameter-detail-table.html
